# Generated by Django 3.0.4 on 2020-03-30 11:47

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('c_address', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('owner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('prop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField(verbose_name=property.models.Customer)),
                ('ptype', models.IntegerField()),
                ('pstatus', models.BooleanField()),
                ('price', models.IntegerField()),
                ('p_address', models.CharField(max_length=50)),
                ('owner_id', models.IntegerField(verbose_name=property.models.owner)),
                ('floor', models.IntegerField()),
                ('p_age', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('cust_id', models.IntegerField(verbose_name=property.models.Customer)),
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('p_age', models.IntegerField()),
                ('size', models.IntegerField()),
                ('area', models.CharField(max_length=10)),
                ('ptype', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('cust_id', models.IntegerField(verbose_name=property.models.Customer)),
                ('owner_id', models.IntegerField(verbose_name=property.models.owner)),
                ('prop_id', models.IntegerField(verbose_name=property.models.property)),
                ('price', models.IntegerField()),
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
