# Generated by Django 3.0.4 on 2020-03-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Customer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.owner'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Customer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Customer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.owner'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='prop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
