# Generated by Django 3.0.4 on 2020-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_log_in_buyer_log_in_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log_in_buyer',
        ),
        migrations.DeleteModel(
            name='log_in_seller',
        ),
        migrations.AddField(
            model_name='owner',
            name='b_address',
            field=models.CharField(default='Not provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_address',
            field=models.CharField(default='Not provided', max_length=50),
        ),
    ]
