# Generated by Django 3.0.4 on 2020-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200402_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='not provided', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
