# Generated by Django 3.0.4 on 2020-04-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200402_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='not provided', max_length=30),
        ),
        migrations.AddField(
            model_name='owner',
            name='second_name',
            field=models.CharField(default='not provided', max_length=30),
        ),
    ]
