# Generated by Django 3.0.4 on 2020-04-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner_id',
            field=models.CharField(max_length=50),
        ),
    ]
