# Generated by Django 3.0.4 on 2020-04-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20200409_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pname',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
