# Generated by Django 3.0.4 on 2020-04-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_property_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(default='', max_length=10),
        ),
    ]
