# Generated by Django 3.0.4 on 2020-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_property_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pstatus',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='cust_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cust_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='owner_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='prop_id',
            field=models.IntegerField(),
        ),
    ]
