# Generated by Django 3.0.4 on 2020-04-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200410_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
