# Generated by Django 3.0.4 on 2020-04-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='', upload_to='property_manage/images'),
        ),
    ]
