# Generated by Django 3.0.4 on 2020-04-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20200411_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='current',
            new_name='curr',
        ),
    ]
