# Generated by Django 3.0.4 on 2020-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20200411_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
